#include<stdio.h>
#include<conio.h>
#include<iostream.h>
#include<stdlib.h>
main()
{//inicio
  int cantidad de dinero;
  cout<<"ingrese su cantidad de dinero"<<endl;
  cin>>cantidad de dinero;
  if(cantidad de dinero>=251)
  {//inicio del if
  cout<<"compre el anillo"<<cantidad de dinero<<endl;
  }//fin del if
  else
  {//inicio del else
  cout<<"No compre el anillo"<<cantidad de dinero<<endl;
  }//fin del else
  if(cantidad de dinero>=101.00)
  {//inicio del if
  cout<<"compre las flores"<<cantidad de dinero<<endl;
  }//fin del if
  else
  {//inicio del else
  cout<<"No compre las flores"<<cantidad de dinero<<endl;
  }//fin del else
  if(cantidad de dinero>=11.00)
  {//inicio del if
  cout<<"compre los chocolates"<<cantidad de dinero<<endl;
  }//fin del if
  else
  {//inicio del else
  cout<<"No compre los chocolates"<<cantidad de dinero<<endl;
  }//fin del else
  if(cantidad de dinero>=10.00);
  {//inicio del if
  cout<<"compre la tarjeta"<<cantidad de dinero<<endl;
  }//fin del if
  else
  {//inicio del else
  cout<<"No compre la tarjeta"<<cantidad de dinero<<endl;
  }//fin del else
  //return 0;
  //getch();
  }//fin       
