#include<stdio.h>
#include<conio.h>
#include<iostream.h>
#include<windows.h>
main()
{
  int a;
  cout<<"Ingrese el año nacimiento de la persona"<<endl;
  cin>>a;
  if(a>2000 && a<2001);
  {
   cout<<"usted es generacion milenia"<<endl;
  }
  if(a>1949 && a<1965);
  {
   cout<<"usted es generacion baby bom"<<endl;
  }
  if(a>2000 && a<2010);
  {
   cout<<"usted es generacion z"<<endl;
  }
    getch();
  }

